Revert "qcacld-3.0/Kbuild: Don't hardcode WLAN_ROOT to drivers/staging/qcacld-3.0"
* Maybe fix this?
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:27:10: fatal error: 'wlan_hdd_includes.h' file not found
   27 | #include "wlan_hdd_includes.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
  CC      drivers/soc/qcom/secure_buffer.o
  CC      drivers/thermal/gov_low_limits.o
  CC      drivers/thermal/cpu_cooling.o
  CC      drivers/tty/serdev/serdev-ttyport.o
1 error generated.
make[4]: *** [../scripts/Makefile.build:338: drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.o] Error 1
make[3]: *** [../scripts/Makefile.build:642: drivers/staging/qcacld-3.0] Error 2
make[2]: *** [../scripts/Makefile.build:642: drivers/staging] Error 2
make[2]: *** Waiting for unfinished jobs....

This reverts commit 602b03c364644d68b5c4aae806d776baac9b7ebe.

Signed-off-by: ris <rissu.ntk@gmail.com>